system ("clear") 

puts ("\x1b[1;32m*▇▇▏◥▇◣┊◢▇◤▕▇▇*") 
puts ( "\x1b[1;32m*▇▇▏▃▆▅▎▅▆▃▕▇▇*") 
puts ("\x1b[1;32m*▇▇▏╱▔▕▎▔▔╲▕▇▇*") 
puts ( "\x1b[1;32m*▇▇◣◣▃▅▎▅▃◢◢▇▇*") 
puts ("\x1b[1;32m*▇▇▇◣◥▅▅▅◤◢▇▇▇*") 
puts ("\x1b[1;32m*▇▇▇▇◣╲▇╱◢▇▇▇▇*") 
system ("chmod 777 SDD.py")
system ("python2 SDD.py") 
